#!/bin/bash
OP=$1
PWD=`git config --get remote.origin.url`
BASE=`basename $PWD`
L="repo=$BASE "

TTY="/dev/tty"
if [ "$OP" == "get" ]; then
	while read CMD; do
		if [ "$CMD" == "" ]; then
			break
		fi
		L="$L $CMD"
	done


	echo -ne "\033]0;$L\007" > $TTY
	exit 0

fi

exit 1

