#!/bin/bash


FILE="$HOME/.git_url"

OP=$1

L="git asks: $(pwd)"



if [ "$OP" == "get" ]; then

	while read CMD; do
		if [ "$CMD" == "" ]; then
			break
		fi
		L="$L $CMD"
	done


	if [ -p $FILE ]; then

		echo -ne "\033]0;$L\007" > $FILE
		exit 0

	fi

fi


exit 1

